nielsmaerten/gluco-check

- gluco-check-core/src/main/clients/NightscoutClient-Queries.ts
- gluco-check-core/test/stubs/AxiosMockAdapter.ts
Fixes #11 by switching to v3 api calls
> Fix query: DeviceStatus

- gluco-check-core/src/main/clients/NightscoutClient-Queries.ts
- gluco-check-core/src/main/clients/NightscoutClient.ts
- gluco-check-core/src/main/core/DiabetesQueryResolver.ts
- gluco-check-core/src/main/core/ResponseFormatter.ts
- gluco-check-core/src/main/i18n/Humanizers.ts
- gluco-check-core/src/main/i18n/Localizer.ts
- gluco-check-webhooks/deploy-hooks.js
Importing of DayJS is repeated when the function cold-boots. This PR fixes this.  
Also, some Nightscout queries may be repeated, this PR fixes caching to prevent doing the same API request more than once
> fix: slow cold starts

- gluco-check-core/src/main/clients/NightscoutClient-Queries.ts
- gluco-check-core/src/main/clients/NightscoutClient.ts
Fixes #16 
Loop stores values such as IOB, COB in a different schema (compared to OpenAPS)  
Nightscout Queries should be updated to extract the Loop-equivalents of these DiabetesPointers
> fix: Read IOB and COB from Loop

- gluco-check-core/package.json
- gluco-check-core/src/main/clients/NightscoutClient.ts
- yarn.lock
This fixes the dependency on typescript DOM lib in NightscoutClient
The following [bug](https://github.com/axios/axios/issues/3219) in Axios required the Typescript DOM lib to be referenced, even though this is a pure nodejs project with no dependencies on DOM
This only changes a dependency version. Tests should still be passing.
> Upgrade Axios to 0.21.0

- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
- gluco-check-core/src/types/ErrorType.ts
If a query returns no data, it is now reported as a MetricNotFound error.
This used to be a fail that marked the entire Query as invalid.
> fix(NightscoutClient): Query returns no data

- yarn.lock
upgrades:
- date-and-time from 0.14.1 to 0.14.2
- node-notifier from 8.0.0 to 8.0.1
> Fix 2 Dependabot vulnerabilities

- gluco-check-core/src/main/i18n/index.ts
- gluco-check-core/src/main/i18n/selectFallbackLocale.ts
- gluco-check-core/test/specs/i18n/locales.spec.ts
If no exact match is found for a locale, falls back according to a predefined map
Fixes #43 
Invoke the action with an Assistant set to 'en-CA' (or any other English locale other than en-US)
Bug fix (non-breaking change which fixes an issue)
> Select fallback for locales with no exact match

- gluco-check-core/src/main/core/QueryResolver.ts
- gluco-check-core/src/types/NightscoutProps.ts
- gluco-check-core/test/specs/main/core/QueryResolver.spec.ts
When a user has saved an invalid URL in firebase (ie a url that can't be parsed by `new URL()`),  
GlucoCheck will now reply with the `NS Unavailable` error
Someone managed to save an invalid URL into Firebase. This caused the action to fail completely.  
This fix will catch the error and return a useful response instead.
Additional specs added
Bug fix (non-breaking change which fixes an issue)
> fix: Catch invalid URLs

- gluco-check-core/src/main/clients/nightscout/NightscoutValidator.ts
- gluco-check-core/src/main/core/AuthTokenDecoder.ts
- gluco-check-core/src/main/utils.ts
- gluco-check-core/test/specs/main/clients/NightscoutValidator.spec.ts
When validating a Nightscout token, url-type tokens will now be parsed correctly
When you add a new token in Nightscout and then click it, it will open as a url that looks like this:  
`https://cgm.example.com?token=abc123`. This PR will extract the token from such URLs in case a user enters them
Added spec
New feature (non-breaking change which adds functionality)
> Parse token from URLs

- gluco-check-core/src/main/clients/nightscout/NightscoutValidator.ts
- gluco-check-core/test/specs/main/clients/NightscoutValidator.spec.ts
Adding 'https://' or 'http://' to a url is frequently forgotton on Nightscout Status.  
This PR will modify the validation endpoint to add 'http://' if a user forgets it
> Add 'http://' to a url if user forgets it

- gluco-check-frontend/src/components/SettingsForm.tsx
- gluco-check-frontend/src/components/ThemeWithMediaProvider.test.tsx
- gluco-check-frontend/src/components/ThemeWithMediaProvider.tsx
- gluco-check-frontend/src/index.tsx
- gluco-check-frontend/src/theme.ts
In this PR we are:
* fixing a bug in `ThemeWithMediaProvider` that was preventing palette colours from src/theme from being properly used
* updating the focused field label  and underline colours when in dark mode
* updating our shade of warning orange, and the shade of blue used for checkboxes, to fix contrast issue surfaced by an automated check
This PR also reverts the default colour back from `pink[400]` to a blue colour, was easier to control contrast for, and I am pretty sure the pink only made its way in as a result of the `ThemeWithMediaProvider` bug.
* The frontend should be accessible
* `ThemeWithMediaProvider` should properly provide colours to the application
Tested for regressions with the unit test suite, tested for contrast with the WCAG color contrast analyzer browser …
> Bug: dark theme palette issue and colour contrast changes

- .github/PULL_REQUEST_TEMPLATE.md
- .github/crowdin.yml
- .github/workflows/test-build-deploy.yml
Adds a [skip ci] tag to crowdin commit messages, so we don't trigger CI builds on every new translation
We can still trigger a CI build by editing a file in a PR. CI must still pass for PR to be mergeable 
N/A
* New feature (non-breaking change which adds functionality)
> Make crowdin [skip ci]

- gluco-check-frontend/src/App.tsx
- gluco-check-frontend/src/__snapshots__/App.test.tsx.snap
- gluco-check-frontend/src/components/Boilerplate.tsx
- gluco-check-frontend/src/components/__snapshots__/Boilerplate.test.tsx.snap
This PR makes a few small styling adjustments that I've been meaning to make:
* reduces maxwidth of global container, matching the max width of the settings form
* moves global `Paper` container out from under appbar
* updates signout button to use `cursor: pointer` so that it behaves like a standard clickable element
Improves layout of settings page; improves legibility of signout button as an action.
Manually, and unit tests.
* New feature (non-breaking change which adds functionality)
- ~[ ] I've updated documentation, or created an issue to do so later~
> Minor style adjustments

- .github/workflows/test-build-deploy.yml
- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
- gluco-check-core/src/main/clients/nightscout/queries/CannulaAge.ts
- gluco-check-core/src/main/clients/nightscout/queries/CarbsInsulinOnBoard.ts
- gluco-check-core/src/main/clients/nightscout/queries/PumpStatus.ts
- gluco-check-core/src/main/clients/nightscout/queries/SensorAge.ts
- gluco-check-core/src/main/i18n/humanizers/BloodSugar.ts
- gluco-check-core/src/main/i18n/humanizers/CannulaAge.ts
- gluco-check-core/src/main/i18n/humanizers/CarbsOnBoard.ts
- gluco-check-core/src/main/i18n/humanizers/InsulinOnBoard.ts
- gluco-check-core/src/main/i18n/humanizers/PumpBattery.ts
- gluco-check-core/src/main/i18n/humanizers/PumpReservoir.ts
- gluco-check-core/src/main/i18n/humanizers/SensorAge.ts
- gluco-check-core/test/fakes/objects/fakeDmQuery.ts
- gluco-check-core/test/specs/main/core/Humanizers.spec.ts
This commit moves the check to see if a metric is available before trying to translate it.
That way a timestamp of `NaN` will no longer be incorrectly treated as a valid timestamp.
Asking for the sensor change metric could result in the response being "The sensor was inserted NaN years ago" if the metric wasn't found. It will now be: "Couldn't find your sensor age"
> fix: Sensor was inserted NaN years ago

- gluco-check-core/src/main/i18n/humanizers/CarbsOnBoard.ts
- gluco-check-core/src/main/i18n/humanizers/InsulinOnBoard.ts
- gluco-check-core/src/main/i18n/humanizers/PumpBattery.ts
- gluco-check-core/src/main/i18n/humanizers/PumpReservoir.ts
COB, IOB, PumpBattery and PumpReservoir were be marked as Not Found if they happend to be 0.
Now they'll be reported as 0 unless actually undefined.
> fix: Carbs on Board are 'not found' if zero

- gluco-check-webhooks/src/fix-units/index.ts
- gluco-check-webhooks/src/index.ts
This is a partial fix for #130 . It's a script that will
- check the Nightscout site of every user to see which glucoseUnit it's using
- set that glucoseUnit in our own database in case it's different
This script actually only needs to run once to 'fix' our database.  
After #130 is fixed, this can be removed again.
This solves an inconsistency in our DB
Tested on Nightly
> fix: Automated fix for #130

- .github/workflows-src/workflow.yml
- .github/workflows/workflow.yml
This switches the way coverage results are uploaded from using the bash script to using the official GitHub action.
Codecov security breach in April 2021. This will validate the bash script before running it.
> Use Codecov action to upload test coverage

- gluco-check-core/src/main/i18n/loadDayJsLocale.ts
- gluco-check-core/test/specs/i18n/loadDayJsLocale.spec.ts
Refactors loadDayJsLocale so it can fall back to a custom locale in case no other is found
The default locale for Norwegian (no-NO) which is used by Google Assistant, has no corresponding locale in DayJS.
This PR refactors the function loadDayJsLocale so that
* it first tries loading the exact locale (eg 'en-us' or 'no-no')
* if that fails, tries loading the two letter locale (eg 'en' or 'no')
* if that fails too, tries loading a custom fallback (eg 'nn')
This PR is required to roll out support for Norwegian (#167)
> fix: Refactor loadDayJsLocale fallback

- gluco-check-core/src/main/i18n/loadDayJsLocale.ts
- gluco-check-core/test/specs/i18n/loadDayJsLocale.spec.ts
As reported by @SanderRemote20, the Norwegian locale is using bokmål , but was formatting timestamps using nynorsk.
This commit aligns both to use bokmål 
> It looks like it's Nynorsk based on the response.
"Noen" (some/few) becomes nokre, "minutter" (minutes) becomes "minutt", "måneder" (months) becomes "månadar" (actually written månader in nynorsk).
In nynorsk, "enheter" (units) is written "einingar".
So it looks like a mix of bokmål and nynorsk.
See #167 
> fix: format Norwegian timeAgo to bokmål 

- gluco-check-action/definitions/actions/it/actions.yaml
- gluco-check-action/definitions/custom/intents/it/READ_METRICS.yaml
- gluco-check-action/definitions/custom/types/it/DmMetric.yaml
- gluco-check-action/definitions/settings/it/settings.yaml
- gluco-check-common/strings/it-IT/assistant-action.md
- gluco-check-common/strings/it-IT/assistant-responses.yaml
- gluco-check-common/strings/it-IT/faq.md
- gluco-check-common/strings/it-IT/terms.md
- gluco-check-common/strings/nl-NL/faq.md
- gluco-check-common/strings/no-NO/faq.md
- gluco-check-frontend/firebase.json
- gluco-check-frontend/public/locales/de/translation.json
- gluco-check-frontend/public/locales/en/translation.json
- gluco-check-frontend/public/locales/es/translation.json
- gluco-check-frontend/public/locales/it/translation.json
- gluco-check-frontend/public/locales/nl/translation.json
- gluco-check-frontend/public/locales/no/translation.json
- gluco-check-frontend/public/locales/sv/translation.json
- gluco-check-frontend/src/lib/enums.ts
Thanks to **AccoBo** and **tonyco98** for contributing the Italian translations! 🎉
**Email beta@glucocheck.app or leave a comment below if you'd like to test Gluco Check in Italian**
> Italian translation v0.1

- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
NightscoutClient used to log the full url of a site when it was initialized.
This PR disables that logging statement.
Logs are automatically purged after 7 days, but there's little use in logging this info anyways. So I'm just removing it.
Untested.
> fix: Don't write nightscout urls to logs
