nielsmaerten/gluco-check

- gluco-check-action/settings/settings.PROD.yaml
- gluco-check-action/settings/settings.yaml
- gluco-check-action/webhooks/ActionsOnGoogleFulfillment.yaml
Extends yaml files for the Google Action with directory information, and adds sections for nightly vs production env
gactions pull and gactions push; gactions deploy preview
> chore: Reorganize actions yaml

- gluco-check-core/package.json
- gluco-check-webhooks/package.json
- yarn.lock
This upgrades dependencies across all packages to their latest version
> Upgrade all dependencies

- gluco-check-webhooks/src/url-validation/index.ts
This should fix https://github.com/ddamico/gluco-check-frontend-client/pull/25
> fix(webhook): CORS headers on validation endpoint

- gluco-check-common/strings/en/assistant-responses.yaml
- gluco-check-core/src/main/clients/FirebaseClient.ts
- gluco-check-core/src/main/clients/UserProfileClient.ts
- gluco-check-core/src/main/core/ConversationDecoder.ts
- gluco-check-core/src/main/core/ResponseBuilder.ts
- gluco-check-core/src/main/i18n/humanizers/_disclaimer.ts
- gluco-check-core/src/main/i18n/humanizers/index.ts
- gluco-check-core/src/types/User.ts
- gluco-check-core/test/specs/i18n/locales.spec.ts
- gluco-check-core/test/specs/main/core/ResponseBuilder.spec.ts
- gluco-check-core/test/stubs/UserProfileClient.ts
This PR will allow the Actions to mention it's not a doctor when it gives out information.
This is required by Google. All actions dealing with medical data should mention this disclaimer.
New feature (non-breaking change which adds functionality)
> Medical Disclaimers

- gluco-check-core/package.json
- gluco-check-webhooks/package.json
- package.json
- yarn.lock
`yarn upgrade-interactive --latest`
> Upgrade all dependencies to latest version

- yarn.lock
> Upgrade dependency ini to v1.3.8

- .github/workflows/nodejs.yml
- .github/workflows/pr-to-main.yml
- .github/workflows/push-to-main.yml
Github will auto deploy master to Nightly on every update
> Enable cont. deploys

- gluco-check-action/definitions/custom/types/DmMetric.yaml
- gluco-check-action/definitions/custom/types/nl/DmMetric.yaml
- gluco-check-common/strings/en-US/assistant-responses.yaml
- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
- gluco-check-core/src/main/clients/nightscout/queries/DeviceStatus.ts
- gluco-check-core/src/main/i18n/humanizers/DmSnapshot.ts
- gluco-check-core/src/main/i18n/humanizers/PumpReservoir.ts
- gluco-check-core/src/main/i18n/humanizers/index.ts
- gluco-check-core/src/types/DmMetric.ts
- gluco-check-core/src/types/DmSnapshot.ts
- gluco-check-core/test/fakes/objects/fakeDmSnapshot.ts
- gluco-check-core/test/specs/i18n/locales.spec.ts
- gluco-check-core/test/specs/types/DiabetesQuery.spec.ts
Ask how many units are left in the pump's reservoir
Closes #10 
New test added to locale spec.
New feature (non-breaking change which adds functionality)
> Add new DmMetric: PumpReservoir

- gluco-check-common/strings/en-US/assistant-responses.yaml
- gluco-check-common/strings/nl-NL/assistant-responses.yaml
- gluco-check-core/src/main/clients/nightscout/NightscoutValidator.ts
Fixes #48 
Should only pass existing tests
Bug fix (non-breaking change which fixes an issue)
> Fix: validator not correctly reporting readable metrics

- gluco-check-core/src/main/clients/UserProfileClient.ts
- gluco-check-core/src/main/core/ConversationDecoder.ts
- gluco-check-core/src/main/core/ResponseBuilder.ts
- gluco-check-core/src/types/DmQuery.ts
- gluco-check-core/test/specs/main/core/ResponseBuilder.spec.ts
- gluco-check-core/test/stubs/UserProfileClient.ts
This PR will be used to fix various 'small' issues. Maybe also some light code maintenance
- Integrating beta feedback
- Prepping the repo to integrate the frontend-package
Existing tests should pass. No new tests added so far, bc no significant changes.
- Chores, minor fixes.
> Minor fixes

- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
- gluco-check-core/src/main/clients/nightscout/queries/CarbsInsulinOnBoard.ts
- gluco-check-core/src/main/clients/nightscout/queries/DeviceStatus.ts
- gluco-check-core/src/main/clients/nightscout/queries/PumpStatus.ts
- gluco-check-core/src/main/clients/nightscout/queries/index.ts
- gluco-check-core/src/main/i18n/humanizers/DmSnapshot.ts
- gluco-check-core/src/main/i18n/humanizers/index.ts
- gluco-check-core/test/fakes/http-responses/pebble.ts
- gluco-check-core/test/specs/main/clients/NightscoutClient.spec.ts
- gluco-check-core/test/stubs/AxiosMockAdapter.ts
Fixes #54
Tests should be updated to reflect new queries.
Refactoring
> Pull IOB and COB from /pebble endpoint

- .github/workflows/pr-to-main.yml
- .github/workflows/push-to-main.yml
- gluco-check-common/strings/en-US/assistant-responses.yaml
- gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
- gluco-check-core/src/main/clients/nightscout/NightscoutValidator.ts
- gluco-check-core/src/main/core/AuthTokenDecoder.ts
- gluco-check-core/src/main/index.ts
- gluco-check-core/test/stubs/AxiosMockAdapter.ts
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/nielsmaerten/gluco-check/issues).
> Apply fixes from CodeFactor

- gluco-check-core/src/main/core/QueryResolver.ts
- gluco-check-core/src/main/utils.ts
- gluco-check-core/src/types/NightscoutProps.ts
Original hasValidUrl property on NightscoutProps
would be undefined when object is coming from firbase.
> bugfix: Checking if url is valid moved to utils.ts

- gluco-check-action/definitions/settings/settings.yaml
Requested by Google during review:  
Add a disclaimer to the Action's description in the Assistant Directory
> Add disclaimer to description in Actions Directory

- yarn.lock
This fixes a security vulnerability in y18n@4.0.0
> Bump y18n to v4.0.1

- gluco-check-action/.env.example
- gluco-check-action/definitions/custom/intents/READ_METRICS.yaml
This PR adds a few more possible ways to invoke the Action
A few more ways people may try invoking the app
Tested in Actions simulator and on a Pixel 4a
New feature (non-breaking change which adds functionality)
> Add more invocations for Action

- .github/workflows/pr-to-main.yml
- .github/workflows/push-to-main.yml
- .husky/pre-push
- gluco-check-action/package.json
- gluco-check-common/package.json
- gluco-check-core/jest.config.js
- gluco-check-core/package.json
- gluco-check-frontend/package.json
- gluco-check-webhooks/firebase.json
- gluco-check-webhooks/package.json
- package.json
- yarn.lock
In this PR, we're merging the GitHub workflows of frontend & backend together.
> Merge github workflows

- gluco-check-frontend/public/locales/en/translation.json
- gluco-check-frontend/public/locales/nl/translation.json
- gluco-check-frontend/src/App.tsx
- gluco-check-frontend/src/__snapshots__/App.test.tsx.snap
- gluco-check-frontend/src/components/Boilerplate.tsx
- gluco-check-frontend/src/lib/constants.ts
In this PR we are taking URLs previously defined as strings in our translation files, moving them into constants, and removing them from the existing translations files.
The question has now been resolved of whether there would be any value in putting the urls into translations, and since they're not needed there they should be removed.
Unit test suite, manual testing.
* New feature (non-breaking change which adds functionality)
- ~[ ] I've updated documentation, or created an issue to do so later~
> Move URLs out of translations

- gluco-check-action/.env.example
- gluco-check-action/package.json
- gluco-check-common/package.json
- gluco-check-core/package.json
- gluco-check-frontend/package.json
- gluco-check-frontend/src/App.tsx
- gluco-check-frontend/src/components/LanguageSelector.tsx
- gluco-check-webhooks/package.json
- package.json
This PR will prepare the codebase for the release of version 1.3.0 (Multilanguage support)
Dutch version of the Actions has been approved by Google. Ready for release!
Reviewed and approved, tested on simulator and real device.
* New feature (non-breaking change which adds functionality)
> v1.3.0 Prep

- gluco-check-frontend/src/components/SettingsForm.tsx
- gluco-check-frontend/src/components/__snapshots__/SettingsForm.test.tsx.snap
- gluco-check-frontend/src/pages/EditSettings.tsx
Hotfix to deal with #130. This is a temporary fix. We should look into what's causing the actual bug
Tests updated, tested locally
> hotfix: Always display glucoseUnitField

- gluco-check-frontend/src/components/LanguageSelector.test.tsx
- gluco-check-frontend/src/components/LanguageSelector.tsx
Sorts the list of languages in the languageSelector alphabetically
> Sort languages in selector alphabetically

- gluco-check-frontend/firebase.json
- gluco-check-frontend/public/locales/en/translation.json
- gluco-check-frontend/public/locales/es/translation.json
- gluco-check-frontend/public/locales/nl/translation.json
- gluco-check-frontend/public/locales/sv/translation.json
- gluco-check-frontend/src/lib/enums.ts
Enables support for Swedish on the frontend, with a beta warning.  
This PR is part of issue #148 
Describe how you've tested your changes.
Translation
> Enable SV on frontend

- gluco-check-action/definitions/custom/global/actions.intent.NO_INPUT_1.yaml
- gluco-check-action/definitions/custom/global/actions.intent.NO_INPUT_2.yaml
- gluco-check-action/definitions/custom/global/actions.intent.NO_INPUT_FINAL.yaml
- gluco-check-action/definitions/custom/global/actions.intent.NO_MATCH_1.yaml
- gluco-check-action/definitions/custom/global/actions.intent.NO_MATCH_2.yaml
- gluco-check-action/definitions/custom/global/actions.intent.NO_MATCH_FINAL.yaml
- gluco-check-action/definitions/custom/intents/READ_METRICS.yaml
- gluco-check-action/definitions/custom/intents/de/READ_METRICS.yaml
- gluco-check-action/definitions/custom/intents/es/READ_METRICS.yaml
- gluco-check-action/definitions/custom/intents/nl/READ_METRICS.yaml
- gluco-check-action/definitions/custom/prompts/de/static_prompt_5.yaml
- gluco-check-action/definitions/custom/prompts/de/static_prompt_6.yaml
- gluco-check-action/definitions/custom/prompts/de/static_prompt_7.yaml
- gluco-check-action/definitions/custom/prompts/de/static_prompt_8.yaml
- gluco-check-action/definitions/custom/prompts/es/static_prompt_5.yaml
- gluco-check-action/definitions/custom/prompts/es/static_prompt_6.yaml
- gluco-check-action/definitions/custom/prompts/es/static_prompt_7.yaml
- gluco-check-action/definitions/custom/prompts/es/static_prompt_8.yaml
- gluco-check-action/definitions/custom/prompts/nl/static_prompt_5.yaml
- gluco-check-action/definitions/custom/prompts/nl/static_prompt_6.yaml
- gluco-check-action/definitions/custom/prompts/nl/static_prompt_7.yaml
- gluco-check-action/definitions/custom/prompts/nl/static_prompt_8.yaml
- gluco-check-action/definitions/custom/prompts/static_prompt_5.yaml
- gluco-check-action/definitions/custom/prompts/static_prompt_6.yaml
- gluco-check-action/definitions/custom/prompts/static_prompt_7.yaml
- gluco-check-action/definitions/custom/prompts/static_prompt_8.yaml
- gluco-check-action/definitions/custom/scenes/CustomMetrics.yaml
- gluco-check-action/definitions/settings/de/settings.yaml
- gluco-check-action/definitions/webhooks/ActionsOnGoogleFulfillment.yaml
This PR replaces static prompts with calls to the webhook
Simplifying the actions definition
Tested on simulator and in alpha
Updating the intents is also a workaround for this bug:
https://stackoverflow.com/q/69729446
> Reset GoogleActions system intents

- gluco-check-action/definitions/actions/no/actions.yaml
- gluco-check-action/definitions/custom/intents/no/READ_METRICS.yaml
- gluco-check-action/definitions/custom/types/DmMetric.yaml
- gluco-check-action/definitions/custom/types/no/DmMetric.yaml
- gluco-check-action/definitions/settings/no/settings.yaml
- gluco-check-common/strings/no-NO/assistant-action.md
- gluco-check-common/strings/no-NO/assistant-responses.yaml
- gluco-check-common/strings/no-NO/faq.md
- gluco-check-common/strings/no-NO/terms.md
- gluco-check-core/src/main/i18n/index.ts
- gluco-check-frontend/firebase.json
- gluco-check-frontend/public/locales/de/translation.json
- gluco-check-frontend/public/locales/en/translation.json
- gluco-check-frontend/public/locales/es/translation.json
- gluco-check-frontend/public/locales/nl/translation.json
- gluco-check-frontend/public/locales/no/translation.json
- gluco-check-frontend/src/lib/enums.ts
This adds the Norwegian translation contributed by @SanderRemote20
Thank you! 👏
- @SanderRemote20 will get tester access once this has been deployed to the alpha channel
- _If you're someone reading this and you'd like to test as well: leave a message below !_
> Norwegian translation v0.1
